### ISSUE TITLE
These are the features in ES6 that you should know

### ISSUE THREAD

**Issue by jingruzhang** [freeCodeCamp/news-translation#1]
文章：[These are the features in ES6 that you should know](https://www.freecodecamp.org/news/these-are-the-features-in-es6-that-you-should-know-1411194c71cb/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/features-in-es6-should-know.md)
PR 地址：#24
文章分类：前端
注意：**译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将自己的新分支发 Pull Request**。

**Comment by Samhanx** [comment]
翻译认领

**Comment by miyaliu666** [comment]
> 翻译认领

好的，已标注为翻译中:)
