### ISSUE TITLE
Before you can master design, you must first master the fundamentals

### ISSUE THREAD

**Issue by jingruzhang** [freeCodeCamp/news-translation#10]
文章：[Before you can master design, you must first master the fundamentals](https://www.freecodecamp.org/news/before-you-can-master-design-you-must-first-master-the-fundamentals-1981a2af1fda/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/before-master-design-first-master-the-fundamentals.md)
PR 地址：
文章分类：设计
注意：**译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将自己的新分支发 Pull Request**。

**Comment by TechQuery** [comment]
原文网址不对……

**Comment by jingruzhang** [comment]
> 原文网址不对……

谢谢 @TechQuery 修改好了～

**Comment by jingruzhang** [comment]
翻译认领
