### ISSUE TITLE
[Auto]（在浏览器点击URL之后发生了什么）

### ISSUE THREAD

**Issue by PapayaHUANG** [freeCodeCamp/news-translation#1006]
- 原文网址：[What happens when you click on a URL in your browser](https://www.freecodecamp.org/news/what-happens-when-you-hit-url-in-your-browser/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/what-happens-when-you-hit-url-in-your-browser.md

**Comment by PapayaHUANG** [comment]
@miyaliu666  这篇翻译完毕

**Comment by miyaliu666** [comment]
我这边看到的 你只提交了一次，是不是忘记提交了？@PapayaHUANG

**Comment by PapayaHUANG** [comment]
> 

对！我才发现，刚提交上去了 哈哈哈
