### ISSUE TITLE
[Auto]（Express+Node.js手册）

### ISSUE THREAD

**Issue by PapayaHUANG** [freeCodeCamp/news-translation#1008]
- 原文网址：[The Express + Node.js Handbook – Learn the Express JavaScript Framework for Beginners [2022 Edition]](https://www.freecodecamp.org/news/the-express-handbook/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/the-express-handbook.md

**Comment by Celqaz** [comment]
认领翻译 @miyaliu666

**Comment by miyaliu666** [comment]
PapayaHuang 已经在翻译这篇文章了，她 7 天前创建 PR 了。你可以认领别的文章，谢谢~ @Celqaz

**Comment by Celqaz** [comment]
> PapayaHuang 已经在翻译这篇文章了，她 7 天前创建 PR 了。你可以认领别的文章，谢谢~ @Celqaz

哦哦，好的，上午没有注意到，谢谢～
