### ISSUE TITLE
How to build a CLI tool in NodeJS 💻

### ISSUE THREAD

**Issue by jingruzhang** [freeCodeCamp/news-translation#11]
文章：[How to build a CLI tool in NodeJS 💻](https://www.freecodecamp.org/news/how-to-build-a-cli-tool-in-nodejs-bc4f67d898ec/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/build-cli-tool-in-nodejs.md)
PR 地址：
文章分类：后端
注意：**译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将自己的新分支发 Pull Request**。

**Comment by blackcai** [comment]
翻译认领

**Comment by blackcai** [comment]
[如何在NodeJS中构建CLI工具]#45

**Comment by blackcai** [comment]
刚想起，我似乎把图给搞没了，如果大佬们还没开始校对的话先等等，这周内把图补上去……。

**Comment by miyaliu666** [comment]
还没开始校对，如果校对的话会标注 Review-in-progress 标签的

**Comment by blackcai** [comment]
仔细看了下不知道图片怎么怎么弄，坐等大佬们操作。

**Comment by miyaliu666** [comment]
Translation completed and published. Thanks again!
