### ISSUE TITLE
About freeCodeCamp - Frequently Asked Questions

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#116]
文章：[About freeCodeCamp - Frequently Asked Questions](https://www.freecodecamp.org/news/about/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/about-freeCodeCamp-frequently-asked-questions.md)
PR 地址：

**Comment by Mayankjh** [comment]
Can you please assign me this issue

**Comment by miyaliu666** [comment]
Hi @Mayankjh, I appreciate your help. But is that Google translate? We need some contributor speaking Chinese to review it then, maybe, me😄

**Comment by Mayankjh** [comment]
> Hi @Mayankjh, I appreciate your help. But is that Google translate? We need some contributor speaking Chinese to review it then, maybe, me😄

To be honest Yes, it is😅😅😅

**Comment by raisedadead** [comment]
Hi @Mayankjh thanks for your help. We are unable to accept PRs that are machine translated as is.
