### ISSUE TITLE
How to make your app's architecture secure right now: separation, configuration, and access

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#118]
文章：[How to make your app's architecture secure right now: separation, configuration, and access](https://www.freecodecamp.org/news/secure-application-basics/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/secure-application-basics.md)
PR 地址：

**Comment by ZivLi** [comment]
@miyaliu666 hello，请问下为什么我创建完上面那个 PR，但是在 patch 中搜索不到这个文章。是我哪里操作有问题，还是整个文章已经被删了？
Look forward to your soonest reply.

**Comment by miyaliu666** [comment]
@ZivLi 这是你的 patch 中的文章：https://github.com/ZivLi/news-translation/blob/patch-1/chinese/articles/secure-application-basics.md

需要按照 md 文件名来搜索。

谢谢参与翻译协作！

**Comment by ZivLi** [comment]
@miyaliu666 Done, help review plz.
第一次做这种翻译，期待您的宝贵意见~

**Comment by ZivLi** [comment]
@miyaliu666 请问我还需要做什么么~

**Comment by miyaliu666** [comment]
@ZivLi 谢谢你翻译这篇文章！我稍后会校对，给你留言。最近我们在翻译和校对课程上花时间多一点。谢谢你的耐心等待！

我们每周六下午 1 点 -  3 点组织在线译者交流会，如果你感兴趣参与的话，可以加小助手微信（fcczhongguo），给你发送会议室链接。

这是关于交流会的[介绍](https://chinese.freecodecamp.org/forum/t/topic/1981)。
