### ISSUE TITLE
ES5 to ESNext — here’s every feature added to JavaScript since 2015

### ISSUE THREAD

**Issue by jingruzhang** [freeCodeCamp/news-translation#12]
文章：[ES5 to ESNext — here’s every feature added to JavaScript since 2015](https://www.freecodecamp.org/news/es5-to-esnext-heres-every-feature-added-to-javascript-since-2015-d0c255e13c6e/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/es5-to-esnext—every-feature-added-to-javascript-since-2015.md)
PR 地址：

**Comment by chumzhou** [comment]
认领翻译

**Comment by Cute233** [comment]
认领翻译

**Comment by jingruzhang** [comment]
> 认领翻译
Dear @Cute233 
@chumzhou 已经认领这篇文章啦～

**Comment by miyaliu666** [comment]
Hi @Cute233 ，上一位译者因为最近工作忙，停止翻译这篇文章了，如果你有兴趣的话可以再认领😄

**Comment by blackcai** [comment]
这篇文章已经有其它翻译小组翻译过了，地址：[ES5 to ESNext —  自 2015 以来 JavaScript 新增的所有新特性](https://github.com/lightningminers/article/issues/35)。发布文章的时候可以联系对方管理员。
