### ISSUE TITLE
How you can improve your workflow using the JavaScript console

### ISSUE THREAD

**Issue by jingruzhang** [freeCodeCamp/news-translation#13]
文章：[How you can improve your workflow using the JavaScript console](https://www.freecodecamp.org/news/how-you-can-improve-your-workflow-using-the-javascript-console-bdd7823a9472/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/improve-workflow-using-javascript-console.md)
PR 地址：

**Comment by heruifeng1** [comment]
翻译认领
