### ISSUE TITLE
Inside Afghanistan’s friendliest coding club

### ISSUE THREAD

**Issue by jingruzhang** [freeCodeCamp/news-translation#14]
文章：[Inside Afghanistan’s friendliest coding club](https://www.freecodecamp.org/news/inside-afghanistans-friendliest-coding-club-d553719579e/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/inside-afghanistans-friendliest-coding-club.md)
PR 地址：
文章分类：社区运营
注意：**译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将自己的新分支发 Pull Request**。

**Comment by TechQuery** [comment]
https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/inside-afghanistans-friendliest-coding-club.md

**Comment by jingruzhang** [comment]
亲爱的@TechQuery ，让校对者发现你的译文的唯一方式是发送pull requests，这样直接comment在issue上是不会生成pr的哦

我把[协作流程](https://github.com/freeCodeCamp/news-translation/wiki/%E5%8D%8F%E4%BD%9C%E6%B5%81%E7%A8%8B)的这部分内容粘贴出来给你参考～
译者 Fork 此仓库后找到要认领的文章的 Markdown 文件，在该 Markdown 文件上做翻译。注意：译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将这个分支发 Pull Request。
翻译完成，发送 Pull Request，Pull Request 的标题为所翻译文章的中文标题，内容请注明对应的 Issue 链接，方便进行管理。

谢谢 @TechQuery !
