### ISSUE TITLE
Progressive Web Apps 101: the What, Why and How

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#142]
文章：[Progressive Web Apps 101: the What, Why and How](https://www.freecodecamp.org/news/progressive-web-apps-101-the-what-why-and-how-4aa5e9065ac2/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/progressive-web-apps-101-the-what-why-and-how.md)
PR 地址：

**Comment by miyaliu666** [comment]
本文需要和 issue#68 同时认领喔

**Comment by azzinoths0905** [comment]
#142

**Comment by miyaliu666** [comment]
Translation completed and published. Thanks a lot!
