### ISSUE TITLE
Learning Python: From Zero to Hero

### ISSUE THREAD

**Issue by jingruzhang** [freeCodeCamp/news-translation#15]
文章：[Learning Python: From Zero to Hero](https://www.freecodecamp.org/news/learning-python-from-zero-to-hero-120ea540b567/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/learning-python-from-zero-to-hero.md)
PR 地址：
文章分类：后端
注意：**译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将自己的新分支发 Pull Request**。

**Comment by Samhanx** [comment]
翻译认领
