### ISSUE TITLE
Web Development in 2020: What You Should Learn

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#150]
文章：[Web Development in 2020: What You Should Learn](https://www.freecodecamp.org/news/web-development-2020/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/web-development-2020.md)
PR 地址：

**Comment by tanjiarui15** [comment]
翻译认领

**Comment by miyaliu666** [comment]
Translation completed and published. Thanks a lot!
