### ISSUE TITLE
How to Build a Chatbot with React React 项目实践——创建一个聊天机器人

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#156]
文章：[How to Build a Chatbot with React React 项目实践——创建一个聊天机器人](https://www.freecodecamp.org/news/how-to-build-a-chatbot-with-react/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/how-to-build-a-chatbot-with-react.md)
PR 地址：

**Comment by Humilitas** [comment]
翻译认领

**Comment by miyaliu666** [comment]
谢谢！可以直接 pull request 啦~

提醒一下：你翻译的上篇文章我已经发布到 freeCodeCamp 微信公众号和[专栏](https://chinese.freecodecamp.org/news/how-to-create-and-publish-a-vue-component-library/)，等你把邮箱发我，就邀请你成为专栏作者哦，我在[这里](https://github.com/freeCodeCamp/news-translation/pull/238)留言了。

**Comment by Humilitas** [comment]
翻译结果不理想，麻烦 @miyaliu666 将文章重新开放，谢谢~

**Comment by miyaliu666** [comment]
@Humilitas 好的，已经重新开放，谢谢！
