### ISSUE TITLE
How to be a successful software engineer

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#164]
文章：[How to be a successful software engineer](https://www.freecodecamp.org/news/how-to-be-a-successful-software-engineer-6f82a5b1a82e/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/how-to-be-a-successful-software-engineer.md)
PR 地址：

**Comment by luojiyin1987** [comment]
@miyaliu666   我来翻译

**Comment by luojiyin1987** [comment]
@miyaliu666   已经翻译完。
