### ISSUE TITLE
How to create a free static site with GitHub Pages in 10 minutes 使用 GitHub Pages，10 分钟搭建静态网页

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#168]
文章：[How to create a free static site with GitHub Pages in 10 minutes 使用 GitHub Pages，10 分钟搭建静态网页](https://www.freecodecamp.org/news/create-a-free-static-site-with-github-pages-in-10-minutes/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/create-a-free-static-site-with-github-pages-in-10-minutes.md)
PR 地址：

**Comment by muming971208** [comment]
认领校对

**Comment by miyaliu666** [comment]
@muming971208 这篇文章已经 merge 了，已经发布，抱歉我忘记把 review-awaiting 标签改为 published。你可以再找别的 review-awaiting 文章进行校对哦。
