### ISSUE TITLE
How to run GETH from a Docker container

### ISSUE THREAD

**Issue by jingruzhang** [freeCodeCamp/news-translation#17]
文章：[How to run GETH from a Docker container](https://www.freecodecamp.org/news/how-to-run-geth-from-a-docker-container-b6d30620ca74/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/run-geth-from-docker-container.md)
PR 地址：
文章分类：后端
注意：**译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将自己的新分支发 Pull Request**。

**Comment by TechQuery** [comment]
这篇原文咋这么短？正文被隐藏了？

**Comment by jingruzhang** [comment]
> 这篇原文咋这么短？正文被隐藏了？

好像是原文出了问题……我们看看
