### ISSUE TITLE
How to build real-time applications using WebSockets with AWS API Gateway and Lambda 使用 WebSockets，AWS API Gateway 和 Lambda 创建实时应用程序

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#171]
文章：[How to build real-time applications using WebSockets with AWS API Gateway and Lambda 使用 WebSockets，AWS API Gateway 和 Lambda 创建实时应用程序](https://www.freecodecamp.org/news/real-time-applications-using-websockets-with-aws-api-gateway-and-lambda-a5bb493e9452/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/real-time-applications-using-websockets-with-aws-api-gateway-and-lambda.md)
PR 地址：

**Comment by ZhichengChen** [comment]
@miyaliu666 这个` 认领 Markdown 文件：文件地址` 的文件地址有误
