### ISSUE TITLE
How To Master Async/Await With This Real World Example

### ISSUE THREAD

**Issue by jingruzhang** [freeCodeCamp/news-translation#18]
文章：[How To Master Async/Await With This Real World Example](https://www.freecodecamp.org/news/how-to-master-async-await-with-this-real-world-example-19107e7558ad/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/master-async-await-with-real-world-example.md)
PR 地址：[#19](https://github.com/freeCodeCamp/news-translation/pull/19)
文章分类：前端
注意：**译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将自己的新分支发 Pull Request**。

**Comment by zlv2s** [comment]
翻译认领

**Comment by miyaliu666** [comment]
Translation completed and published. Thanks!
