### ISSUE TITLE
How to Use MySQL With Deno and Oak 使用 Deno + Oak 连接 MySQL 指南

### ISSUE THREAD

**Issue by hylerrix** [freeCodeCamp/news-translation#206]
文章：[How to Use MySQL With Deno and Oak 使用 Deno + Oak 连接 MySQL 指南](https://www.freecodecamp.org/news/how-to-use-mysql-in-deno-oak/)
认领 Markdown 文件：
PR 地址：

**Comment by miyaliu666** [comment]
Translation completed and published. Thanks a lot!
