### ISSUE TITLE
Landing My First Development Job - What a Crazy Journey!

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#21]
文章：[Landing My First Development Job - What a Crazy Journey!](https://www.freecodecamp.org/news/landing-my-first-development-job-what-a-crazy-journey/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/landing-my-first-development-job-what-a-crazy-journey.md)
PR 地址：#27
文章分类：其他
注意：译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将自己的新分支发 Pull Request。

**Comment by lingziyb** [comment]
翻译认领

**Comment by miyaliu666** [comment]
Translation completed and published. Thanks again!
