### ISSUE TITLE
How to Automate Your Blog Post Publishing Process with Typescript 如何使用 Typescript 实现自动化发布文章

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#212]
文章：[How to Automate Your Blog Post Publishing Process with Typescript 如何使用 Typescript 实现自动化发布文章](https://www.freecodecamp.org/news/automating-my-blog-posts-publishing-process-with-typescript/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/automating-my-blog-posts-publishing-process-with-typescript.md)
PR 地址：

**Comment by tanjiarui15** [comment]
翻译认领

**Comment by miyaliu666** [comment]
@tanjiarui15 谢谢翻译本文！译文整体比较流畅，我做了些修改，已发布到 [freeCodeCamp 专栏](https://chinese.freecodecamp.org/news/automating-my-blog-posts-publishing-process-with-typescript/)和微信公众号。
