### ISSUE TITLE
Front End Developer vs Back End Developer – Definition and Meaning In Practice 前端和后端的区别到底是什么？非程序员也能读懂！

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#215]
文章：[Front End Developer vs Back End Developer – Definition and Meaning In Practice 前端和后端的区别到底是什么？非程序员也能读懂！](https://www.freecodecamp.org/news/front-end-developer-vs-back-end-developer-definition-and-meaning-in-practice/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/front-end-developer-vs-back-end-developer-definition-and-meaning-in-practice.md)
PR 地址：

**Comment by lihkai01** [comment]
翻译认领

**Comment by miyaliu666** [comment]
@lihkai01 欢迎参加本周六下午 1 点 - 3 点的线上翻译工作坊，了解更多 freeCodeCamp 翻译计划，分享你的建议。可以加我微信 Hello_MrT 吗？到时候我把会议链接发给你。谢谢！

（如本仓库 [readme](https://github.com/freeCodeCamp/news-translation) 介绍）一般情况下，是每周六晚上 7 点半 - 9 点半在腾讯会议组织工作坊，这周是临时调整。
