### ISSUE TITLE
The Nine Most Common Mistakes Developers Make in JavaScript (and How to Fix Them) JavaScript 编程中最常见的 9 个错误

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#221]
文章：[The Nine Most Common Mistakes Developers Make in JavaScript (and How to Fix Them) JavaScript 编程中最常见的 9 个错误](https://www.freecodecamp.org/news/nine-most-common-mistakes-developers-make-in-javascript/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/nine-most-common-mistakes-developers-make-in-javascript.md)
PR 地址：

**Comment by TriDiamond** [comment]
翻译认领

**Comment by miyaliu666** [comment]
已修改标签，接下来你可以根据 readme 中翻译指南的说明，直接提交 PR 哦，谢谢：D

**Comment by miyaliu666** [comment]
@TriDiamond 你好，这篇文章你要继续翻译吗？如果你最近没有时间翻译的话，我想把它开放给其他贡献者认领。如有任何问题，可以加我微信 Hello_MrT 随时交流。
