### ISSUE TITLE
How to Build a Todo App with React, TypeScript, NodeJS, and MongoDB 如何用 React，TypeScript，NodeJS 和 MongoDB 搭建待办事项 App

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#228]
文章：[How to Build a Todo App with React, TypeScript, NodeJS, and MongoDB 如何用 React，TypeScript，NodeJS 和 MongoDB 搭建待办事项 App](https://www.freecodecamp.org/news/how-to-build-a-todo-app-with-react-typescript-nodejs-and-mongodb/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/how-to-build-a-todo-app-with-react-typescript-nodejs-and-mongodb.md)
PR 地址：

**Comment by cyanxxx** [comment]
翻译认领

**Comment by miyaliu666** [comment]
好的，你安装 readme 里的[步骤](https://github.com/freeCodeCamp/news-translation/blob/master/Contributing.md) pull request、开始翻译吧，谢谢！

**Comment by miyaliu666** [comment]
@cyanxxx 谢谢翻译本文！译文很流畅，我做了少量修改，已发布到 [freeCodeCamp 专栏](https://chinese.freecodecamp.org/news/how-to-build-a-todo-app-with-react-typescript-nodejs-and-mongodb/)和微信公众号。

**Comment by miyaliu666** [comment]
@cyanxxx 欢迎参加本周六下午 1 点 - 3 点的线上翻译工作坊，了解更多 freeCodeCamp 翻译计划，分享你的建议。可以加我微信 Hello_MrT 吗？到时候我把会议链接发给你。谢谢！

（如本仓库 [readme](https://github.com/freeCodeCamp/news-translation) 介绍）一般情况下，是每周六晚上 7 点半 - 9 点半在腾讯会议组织工作坊，这周是临时调整。
