### ISSUE TITLE
How to Create and Publish a Vue Component Library 如何搭建、发布一个 Vue 组件库

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#229]
文章：[How to Create and Publish a Vue Component Library 如何搭建、发布一个 Vue 组件库](https://www.freecodecamp.org/news/how-to-create-and-publish-a-vue-component-library/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/how-to-create-and-publish-a-vue-component-library.md)
PR 地址：

**Comment by Humilitas** [comment]
翻译认领

**Comment by miyaliu666** [comment]
谢谢参与翻译！请参照 readme 中的[译者指南](https://github.com/freeCodeCamp/news-translation/blob/master/Contributing.md) pull request 吧：D
