### ISSUE TITLE
What is npm? A Node Package Manager Tutorial for Beginners 写给初学者的编程教程：什么是 npm？

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#243]
文章：[What is npm? A Node Package Manager Tutorial for Beginners 写给初学者的编程教程：什么是 npm？](https://www.freecodecamp.org/news/what-is-npm-a-node-package-manager-tutorial-for-beginners/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/what-is-npm-a-node-package-manager-tutorial-for-beginners.md)
PR 地址：

**Comment by nsuedu** [comment]
翻译认领

**Comment by miyaliu666** [comment]
@nsuedu 好的，请按照[步骤](https://github.com/freeCodeCamp/news-translation/blob/master/Contributing.md) pull request 吧，谢谢！
