### ISSUE TITLE
AJAX Tutorial: What AJAX Is and How to Use it 写给初学者的编程教程：ajax 是什么以及 ajax 如何使用

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#244]
文章：[AJAX Tutorial: What AJAX Is and How to Use it 写给初学者的编程教程：ajax 是什么以及 ajax 如何使用](https://www.freecodecamp.org/news/ajax-tutorial/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/ajax-tutorial.md)
PR 地址：

**Comment by luojiyin1987** [comment]
@miyaliu666  翻译完成
