### ISSUE TITLE
How JavaScript Works: Under the Hood of the V8 Engine JavaScript 到底是怎么运行的

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#248]
文章：[How JavaScript Works: Under the Hood of the V8 Engine JavaScript 到底是怎么运行的](https://www.freecodecamp.org/news/javascript-under-the-hood-v8/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/javascript-under-the-hood-v8.md)
PR 地址：

**Comment by nsuedu** [comment]
认领😇

**Comment by miyaliu666** [comment]
@LianZhuotao 这篇文章你没在翻译的话，就由 @nsuedu 认领翻译，好吗？

**Comment by miyaliu666** [comment]
> 认领😇

@nsuedu 你可以翻译这篇文章啦，谢谢！
另外，欢迎参加本周六下午 1 点 - 3 点的线上翻译工作坊，可以加我微信 Hello_MrT 吗？到时候我把会议链接发给你。
（一般情况下，是每周六晚上 7 点半 - 9 点半组织工作坊，这周是因为 Quincy 要参加，所以我们调整到一个适合大家时区的时间。）

**Comment by luojiyin1987** [comment]
初步翻译完成，感觉好生硬， 我要看一下别的相关资料， 再经行修改。

**Comment by luojiyin1987** [comment]
已经完成翻译。
