### ISSUE TITLE
What is Metaprogramming in JavaScript? In English, please. 什么是 JavaScript 元编程

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#265]
文章：[What is Metaprogramming in JavaScript? In English, please. 什么是 JavaScript 元编程](https://www.freecodecamp.org/news/what-is-metaprogramming-in-javascript-in-english-please/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/edit/master/chinese/articles/what-is-metaprogramming-in-javascript-in-english-please.md)
PR 地址：

**Comment by Humilitas** [comment]
翻译认领
