### ISSUE TITLE
The Linux Command Handbook Linux 命令手册

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#266]
文章：[The Linux Command Handbook Linux 命令手册](https://www.freecodecamp.org/news/the-linux-commands-handbook/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/edit/master/chinese/articles/the-linux-commands-handbook.md)
PR 地址：

**Comment by monstorix** [comment]
认领
