### ISSUE TITLE
JavaScript 字符串反转的三种方式

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#267]
文章：[Three Ways to Reverse a String in JavaScript JavaScript 字符串反转的三种方式](https://www.freecodecamp.org/news/how-to-reverse-a-string-in-javascript-in-3-different-ways-75e4763c68cb/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/edit/master/chinese/articles/how-to-reverse-a-string-in-javascript-in-3-different-ways.md)
PR 地址：

**Comment by nsuedu** [comment]
认领😀

**Comment by nsuedu** [comment]
> 认领😀

#271
