### ISSUE TITLE
JavaScript 中的 Var，Let 和 Const 有什么区别

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#268]
文章：[Var, Let, and Const – What's the Difference? JavaScript 中的 Var，Let 和 Const 有什么区别](https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/edit/master/chinese/articles/var-let-and-const-whats-the-difference.md)
PR 地址：

**Comment by nsuedu** [comment]
认领😀

**Comment by nsuedu** [comment]
> 认领😀

#271
