### ISSUE TITLE
JavaScript 数组教程——如何创建，更新和遍历 JavaScript 对象

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#270]
文章：[JavaScript Array of Objects Tutorial – How to Create, Update, and Loop Through Objects Using JS Array Methods JavaScript 数组教程——如何创建，更新和遍历 JavaScript 对象](https://www.freecodecamp.org/news/javascript-array-of-objects-tutorial-how-to-create-update-and-loop-through-objects-using-js-array-methods/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/edit/master/chinese/articles/javascript-array.md)
PR 地址：

**Comment by nsuedu** [comment]
认领😃

**Comment by miyaliu666** [comment]
好的，已经更新标签~

**Comment by nsuedu** [comment]
> 好的，已经更新标签~

#271
