### ISSUE TITLE
UX 设计教程——绘制线框图

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#276]
文章：[What is a Wireframe? This UX Design Tutorial Will Show You. UX 设计教程——绘制线框图](https://www.freecodecamp.org/news/what-is-a-wireframe-ux-design-tutorial-website/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/edit/master/chinese/articles/what-is-a-wireframe-ux-design-tutorial-website.md)
PR 地址：

**Comment by Humilitas** [comment]
翻译认领
