### ISSUE TITLE
50 道常问的 Java 面试题及答案

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#284]
- 原文网址：[Review these 50 questions to crack your Java programming interview](https://www.freecodecamp.org/news/review-these-50-questions-to-crack-your-java-programming-interview-69d03d746b7f/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/review-these-50-questions-to-crack-your-java-programming-interview.md

**Comment by zhannicholas** [comment]
翻译认领
