### ISSUE TITLE
A crash course in TypeScript

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#29]
文章：[A crash course in TypeScript](https://www.freecodecamp.org/news/a-crash-course-in-typescript-e6bf9c10946/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/a-crash-course-in-typescript.md)
PR 地址：[#34](https://github.com/freeCodeCamp/news-translation/pull/34)
文章分类：前端
注意：译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将自己的新分支发 Pull Request。

**Comment by Tommy-White** [comment]
翻译认领
