### ISSUE TITLE
Git 内部构建可视指南——对象、分支以及如何从头开始创建仓库

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#303]
- 原文网址：[A Visual Guide to Git Internals — Objects, Branches, and How to Create a Repo From Scratch](https://www.freecodecamp.org/news/git-internals-objects-branches-create-repo/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/git-internals-objects-branches-create-repo.md

**Comment by zhannicholas** [comment]
翻译认领
