### ISSUE TITLE
详解 Java 多态

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#304]
- 原文网址：[Polymorphism in Java Tutorial – With Object Oriented Programming Example Code](https://www.freecodecamp.org/news/polymorphism-in-java-tutorial-with-object-oriented-programming-example-code/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/polymorphism-in-java-tutorial-with-object-oriented-programming-example-code.md

**Comment by zhannicholas** [comment]
翻译认领

**Comment by tengfeiwang1** [comment]
mark，后边来学习
