### ISSUE TITLE
每个Web开发者都应该知道的10个JavaScript技巧

### ISSUE THREAD

**Issue by Miever1** [freeCodeCamp/news-translation#307]
- 原文网址：[10 JavaScript Hacks Every Web Developer Should Know](https://www.freecodecamp.org/news/javascript-hacks/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/master/chinese/articles/javascript-hacks.md

**Comment by miyaliu666** [comment]
你似乎没有成功创建 MarkDown 文件，我现在创建一个，然后你按照 readme 里的步骤创建 pull requst 吧。
