### ISSUE TITLE
C 语言入门手册

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#308]
- 原文网址：[The C Beginner's Handbook: Learn C Programming Language basics in just a few hours](https://www.freecodecamp.org/news/the-c-beginners-handbook/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/the-c-beginners-handbook.md

**Comment by zhannicholas** [comment]
翻译认领

**Comment by miyaliu666** [comment]
@zhannicholas 英文专栏最近每周新增 20 多篇文章，你也可以直接看下那里有没有你感兴趣的文章，自己创建待翻译 issue :D

**Comment by zhannicholas** [comment]
> @zhannicholas 英文专栏最近每周新增 20 多篇文章，你也可以直接看下那里有没有你感兴趣的文章，自己创建待翻译 issue :D

最近在看 OSTEP，其中的作业需要使用 C 语言，就当复习了的🤣

**Comment by fnmain** [comment]
翻译认领

**Comment by miyaliu666** [comment]
> 翻译认领

@fnmain 是认领校对吧
