### ISSUE TITLE
The most important skill a programmer can learn

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#31]
文章：[The most important skill a programmer can learn](https://www.freecodecamp.org/news/the-most-important-skill-a-programmer-can-learn-9d410c786baf/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/the-most-important-skill-a-programmer-can-learn.md)
PR 地址：
文章分类：职业发展
注意：译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将自己的新分支发 Pull Request。

**Comment by chumzhou** [comment]
认领翻译

**Comment by luojiyin1987** [comment]
@miyaliu666   我来翻译
