### ISSUE TITLE
REST API 教程

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#310]
- 原文网址：[REST API Tutorial – REST Client, REST Service, and API Calls Explained With Code Examples](https://www.freecodecamp.org/news/rest-api-tutorial-rest-client-rest-service-and-api-calls-explained-with-code-examples/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/rest-api-tutorial.md

**Comment by Humilitas** [comment]
翻译认领。
