### ISSUE TITLE
SQL Joins 教程

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#312]
- 原文网址：[SQL Joins Tutorial: Cross Join, Full Outer Join, Inner Join, Left Join, and Right Join.](https://www.freecodecamp.org/news/sql-joins-tutorial/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/sql-joins-tutorial.md

**Comment by zhannicholas** [comment]
翻译认领

**Comment by miyaliu666** [comment]
@zhannicholas 你的效率太高了，作品又很棒！
