### ISSUE TITLE
Python 完全手册：学 Python，从入门到专业

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#317]
- 原文网址：[The Ultimate Guide to Python: How to Go From Beginner to Pro](https://www.freecodecamp.org/news/the-ultimate-guide-to-python-from-beginner-to-intermediate-to-pro/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/the-ultimate-guide-to-python-from-beginner-to-intermediate-to-pro.md

**Comment by zhannicholas** [comment]
翻译认领
