### ISSUE TITLE
How to build a reusable animation component using React Hooks

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#32]
文章：[How to build a reusable animation component using React Hooks](https://www.freecodecamp.org/news/animating-visibility-with-css-an-example-of-react-hooks/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/animating-visibility-with-css-an-example-of-react-hooks.md)
PR 地址：
文章分类：前端
注意：译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将自己的新分支发 Pull Request。

**Comment by zlv2s** [comment]
翻译认领

**Comment by TechQuery** [comment]
@zlv2s 请编辑这篇文章的 MarkDown 文件，并创建 pull request（在创建时的描述信息框用 `#32` 字样关联本 issue）
