### ISSUE TITLE
OSI 七层模型

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#333]
- 原文网址：[The OSI Model – The 7 Layers of Networking Explained in Plain English](https://www.freecodecamp.org/news/osi-model-networking-layers-explained-in-plain-english/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/master/chinese/articles/osi-model-networking-layers-explained-in-plain-english.md

**Comment by zhannicholas** [comment]
翻译认领
