### ISSUE TITLE
DOM 完全指南

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#338]
- 原文网址：[How to Manipulate the DOM - the Ultimate Beginner's Guide](https://www.freecodecamp.org/news/how-to-manipulate-the-dom-beginners-guide/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/how-to-manipulate-the-dom-beginners-guide.md

**Comment by Humilitas** [comment]
认领翻译。

**Comment by miyaliu666** [comment]
谢谢 @Humilitas 翻译这篇文章。理解 DOM 尤其对初学者应该会很有帮助！
