### ISSUE TITLE
Web 开发中快速配置 VS Code

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#339]
- 原文网址：[How to Set Up VS Code for Web Development in A Few Simple Steps](https://www.freecodecamp.org/news/how-to-set-up-vs-code-for-web-development/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/how-to-set-up-vs-code-for-web-development.md

**Comment by tianheg** [comment]
我认领了这篇
