### ISSUE TITLE
7 Effective Ways To Speed Up Your Site

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#35]
文章：[7 Effective Ways To Speed Up Your Site](https://www.freecodecamp.org/news/seven-ways-to-optimize-your-site-for-speed/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/seven-ways-to-optimize-your-site-for-speed.md)
PR 地址：
文章分类：其他
注意：译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将自己的新分支发 Pull Request。

**Comment by XuQuan-nikkkki** [comment]
翻译认领
