### ISSUE TITLE
将谷歌表格转换为 REST API，在 React 应用中调用

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#363]
- 原文网址：[How to Turn Google Sheets into a REST API and Use it with a React Application](https://www.freecodecamp.org/news/react-and-googlesheets/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/react-and-googlesheets.md

**Comment by ZhichengChen** [comment]
翻译认领

**Comment by ZhichengChen** [comment]
Google Sheets 应该翻译成谷歌表格，Google 有另一款产品 [Google Forms](https://www.google.com/intl/zh-CN/forms/about/)，是谷歌表单的意思
