### ISSUE TITLE
关于原文 Markdown 语法的问题

### ISSUE THREAD

**Issue by tianheg** [freeCodeCamp/news-translation#366]
请问你们用什么工具把网页变成 Markdown 文件呢？为什么文档里会有很多错误的 Markdown 语法呢？[可以看这里](https://github.com/freeCodeCamp/news-translation/runs/1993366606#step:4:37)

我在用 [Copycat](https://chrome.google.com/webstore/detail/copycat/jdjbiojkklnaeoanimopafmnmhldejbg)（一个 Chrome 扩展），它可以很方便地把 HTML 转换成 Markdown 语法的文本。

**Comment by miyaliu666** [comment]
我之前一直用的水歌 @TechQuery 写的：https://git-pager.leanapp.cn/。确实有错误的语法。

谢谢推荐，我会试试看使用 Copycat。

**Comment by TechQuery** [comment]
@tianheg 
HTML 转 Markdown 转换器只做语法处理，并不做**书写规范格式化**，CI 里用的规范检查工具在本地没有问题，放上去就一堆警告，我们在寻找更好用的工具。
