### ISSUE TITLE
The Basic Design Patterns All Developers Need to Know

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#37]
文章：[The Basic Design Patterns All Developers Need to Know](https://www.freecodecamp.org/news/the-basic-design-patterns-all-developers-need-to-know/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/the-basic-design-patterns-all-developers-need-to-know.md)
PR 地址：
文章分类：其他
注意：译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将自己的新分支发 Pull Request。

**Comment by muming971208** [comment]
认领校对
