### ISSUE TITLE
在手机上开发 Web App——Python & Pydroid 安卓应用教程

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#370]
- 原文网址：[How to Build a Web App on Your Phone – Python & Pydroid Android App Tutorial](https://www.freecodecamp.org/news/how-to-code-on-your-phone-python-pydroid-android-app-tutorial/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/how-to-code-on-your-phone-python-pydroid-android-app-tutorial.md

**Comment by ZhichengChen** [comment]
认领翻译
