### ISSUE TITLE
响应式 Web 设计简史

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#372]
- 原文网址：[A Brief History of Responsive Web Design](https://www.freecodecamp.org/news/a-brief-history-of-responsive-web-design/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/a-brief-history-of-responsive-web-design.md

**Comment by ZhichengChen** [comment]
认领翻译
