### ISSUE TITLE
如何处理英语原文的错误

### ISSUE THREAD

**Issue by tianheg** [freeCodeCamp/news-translation#375]
我在阅读 [心理学分析：如何以良好状态提升开发效率](https://chinese.freecodecamp.org/news/how-to-get-things-done-lessons-in-productivity/) 时，阅读了原文 [How to Be Productive, Feel Less Overwhelmed, and Get Things Done](https://www.freecodecamp.org/news/how-to-get-things-done-lessons-in-productivity/)。

发现原文的标题分级可能存在问题，我想反馈，该去哪儿呢？

**Comment by miyaliu666** [comment]
请在[这里](https://github.com/freeCodeCamp/freeCodeCamp/issues/new/choose)发 issue 吧，选择 Bug Report: Issues with /news or guide articles or documentation

**Comment by tianheg** [comment]
好的，知道了，谢谢你
