### ISSUE TITLE
使用 GitHub Action 通过 issue 自动提交待翻译文章到仓库

### ISSUE THREAD

**Issue by tianheg** [freeCodeCamp/news-translation#381]
最新动态：

@stevending1st 已经提交了 Pull Request #389

本地测试成功（@tianheg）

---

主要思路：新建 issue ——> 提交文章到仓库

这一过程通过 GitHub Action 实现自动化提交

这个问题是刚才的 Skype 会议上提出的。我找到了一些参考。大家可以想想，怎么实现。

**参考**：

1. [wayou/turn-issues-to-posts-action](https://github.com/wayou/turn-issues-to-posts-action)

**Comment by tianheg** [comment]
@stevending1st 在生成的文章里，可不可以修改 2 个 Markdown 排版错误：

```markdown
> -   原文地址
> -   原文作者
> -   译者
> -   校对者

1.  Queries
2.  Pages
```

正确排版：

```markdown
> - 原文地址
> - 原文作者
> - 译者
> - 校对者

1. Queries
2. Pages
```

**Comment by stevending1st** [comment]
```markdown
> -   原文地址
> -   原文作者
> -   译者
> -   校对者
```
这个可以修改

 <hr />

```md
1.  Queries
2.  Pages
```
是说在有序列表中，`.` 后面多了一个空格对吗？
如果是这样，我得想想怎么改，好像是库自带的空格。

谢谢您的建议

**Comment by tianheg** [comment]
是的，`.` 后面多了一个空格
