### ISSUE TITLE
如何阅读研究论文——设定研究目标，搜索论文和阅读论文

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#385]
- 原文网址：[How to Read a Research Paper – A Guide to Setting Research Goals, Finding Papers to Read, and More](https://www.freecodecamp.org/news/building-a-habit-of-reading-research-papers/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/blob/main/chinese/articles/building-a-habit-of-reading-research-papers.md

**Comment by zhannicholas** [comment]
翻译认领
