### ISSUE TITLE
如何使用 React 和 React Hooks 创建一个天气应用

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#392]
- 原文网址：[How to Build a Weather Application with React and React Hooks](https://www.freecodecamp.org/news/learn-react-by-building-a-weather-app/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/blob/main/chinese/articles/learn-react-by-building-a-weather-app.md

**Comment by Humilitas** [comment]
认领翻译。
