### ISSUE TITLE
Git 入门指南

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#399]
- 原文网址：[What is Git? A Beginner's Guide to Git Version Control](https://www.freecodecamp.org/news/what-is-git-learn-git-version-control/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/blob/main/chinese/articles/what-is-git-learn-git-version-control.md

**Comment by nemanjajoe** [comment]
认领翻译

**Comment by nemanjajoe** [comment]
Git 入门指南——翻译完成
