### ISSUE TITLE
News Tags

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#4]
文章：[News Tags](https://gist.github.com/scissorsneedfoodtoo/6c4c1fdc130bf540cf6a68d9d37bf3a2)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/news-tags.md)
PR 地址：#131
文章分类：其他
注意：译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将自己的新分支发 Pull Request。

**Comment by miyaliu666** [comment]
[freeCodeCamp Developer News 中文版](https://chinese.freecodecamp.org/news/)已上线，需要把这些英文标签 URL 翻译成中文，然后国外开发者团队会添加到中文版 News 中。
翻译的时候注意一一对照，最好是用两列表格，比如：
https://www.freecodecamp.org/news/tag/front-end/   前端

有的词汇按照咱们中文的使用习惯，不需要翻译，比如：
https://www.freecodecamp.org/news/tag/css3/         CSS3

**Comment by jingruzhang** [comment]
翻译认领

**Comment by tanjiarui15** [comment]
翻译认领

**Comment by miyaliu666** [comment]
谢谢！可以加我微信 Hello_MrT，有什么不清楚的地方可以随时沟通哦 @tanjiarui15
