### ISSUE TITLE
关于 cookies 你需要了解的一切

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#400]
- 原文网址：[Everything You Need to Know About Cookies for Web Development](https://www.freecodecamp.org/news/everything-you-need-to-know-about-cookies-for-web-development/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/blob/main/chinese/articles/everything-you-need-to-know-about-cookies-for-web-development.md

**Comment by ZhichengChen** [comment]
认领翻译
