### ISSUE TITLE
Linux LS 命令

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#401]
- 原文网址：[The Linux LS Command – How to List Files in a Directory + Option Flags](https://www.freecodecamp.org/news/the-linux-ls-command-how-to-list-files-in-a-directory-with-options/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/blob/main/chinese/articles/the-linux-ls-command-how-to-list-files-in-a-directory-with-options.md

**Comment by ZhichengChen** [comment]
认领翻译
