### ISSUE TITLE
使用 AWS SES、Lambda 和 API Gateway 从网站”联系我们“按钮接收邮件

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#407]
- 原文网址：[How to Receive Emails from Your Site's "Contact Us" form Using AWS SES, Lambda, & API Gateway](https://www.freecodecamp.org/news/how-to-receive-emails-via-your-sites-contact-us-form-with-aws-ses-lambda-api-gateway/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/blob/main/chinese/articles/how-to-receive-emails-via-your-sites-contact-us-form-with-aws-ses-lambda-api-gateway.md

**Comment by luojiyin1987** [comment]
认领

**Comment by luojiyin1987** [comment]
@miyaliu666  翻译完成
