### ISSUE TITLE
JavaScript 函数式编程入门指南

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#408]
- 原文网址：[Functional Programming in JavaScript for Beginners](https://www.freecodecamp.org/news/functional-programming-in-javascript-for-beginners/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/blob/main/chinese/articles/functional-programming-in-javascript-for-beginners.md

**Comment by Humilitas** [comment]
认领翻译
