### ISSUE TITLE
[Auto] Terraform 和基础设施即代码

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#441]
- 原文网址：[What is Terraform? Learn Terraform and Infrastructure as Code](https://www.freecodecamp.org/news/what-is-terraform-learn-infrastructure-as-code/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/what-is-terraform-learn-infrastructure-as-code.md

**Comment by luojiyin1987** [comment]
我来翻译 @miyaliu666

**Comment by luojiyin1987** [comment]
#568

**Comment by luojiyin1987** [comment]
@miyaliu666  已经翻译完成
