### ISSUE TITLE
[Auto] 如何防止跨站请求伪造攻击

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#452]
- 原文网址：[Cross Site Request Forgery – What is a CSRF Attack and How to Prevent It](https://www.freecodecamp.org/news/what-is-cross-site-request-forgery/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/what-is-cross-site-request-forgery.md

**Comment by ilam0x** [comment]
translation finished, ready for review.
