### ISSUE TITLE
[Auto] CSS 滚动条教程

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#453]
- 原文网址：[CSS Scrollbar Styling Tutorial – How to Make a Custom Scrollbar](https://www.freecodecamp.org/news/css-scrollbar-tutorial/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/css-scrollbar-tutorial.md

**Comment by Humilitas** [comment]
认领翻译。
