### ISSUE TITLE
[Auto] JavaScript 数组手册（含示例）

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#459]
- 原文网址：[The JavaScript Array Handbook – JS Array Methods Explained with Examples](https://www.freecodecamp.org/news/the-javascript-array-handbook/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/the-javascript-array-handbook.md

**Comment by Humilitas** [comment]
认领翻译。
