### ISSUE TITLE
[Auto] Python 代码示例——面向初学者的示例脚本编程教程

### ISSUE THREAD

**Issue by ywxgod** [freeCodeCamp/news-translation#461]
- 原文网址：[原文标题](https://www.freecodecamp.org/news/路由/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/文章文件名称.md

**Comment by miyaliu666** [comment]
@ywxgod 请问这个 issue 是什么意思呢？

**Comment by ywxgod** [comment]
不好意思，我想翻译这个，但没看懂翻译流程

**Comment by miyaliu666** [comment]
@ywxgod 啊，我们忘记更新翻译指南的第二条了，现在已经更新，请查看[指南](https://github.com/freeCodeCamp/news-translation/blob/main/Contributing.md)。

这篇文章我已经发过 issue 了，请根据指南在我发的 [issue](https://github.com/freeCodeCamp/news-translation/issues/449) 中认领翻译吧。你发的这个我就把它关闭了哈。

如果你还有问题，可以加小助手微信（fcczhongguo）讨论。谢谢！

**Comment by ywxgod** [comment]
好的，晚上回去看看。谢了！
