### ISSUE TITLE
[Auto] 写给新人的指南——如何为开源项目做贡献

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#466]
- 原文网址：[How to Contribute to Open Source Projects – A Beginner's Guide](https://www.freecodecamp.org/news/how-to-contribute-to-open-source-projects-beginners-guide/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/how-to-contribute-to-open-source-projects-beginners-guide.md

**Comment by Blank-Grid** [comment]
closes #466
