### ISSUE TITLE
[Auto] JavaScript 教程——如何创建一个前端项目

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#471]
- 原文网址：[JavaScript Tutorial – How to Set Up a Front End Development Project](https://www.freecodecamp.org/news/how-to-set-up-a-front-end-development-project/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/how-to-set-up-a-front-end-development-project.md

**Comment by luojiyin1987** [comment]
认领

**Comment by luojiyin1987** [comment]
@miyaliu666   翻译完成
