### ISSUE TITLE
[Auto] 学习CSS background 属性

### ISSUE THREAD

**Issue by Miever1** [freeCodeCamp/news-translation#489]
- 原文网址：[Every CSS Background Property Illustrated and Explained with Code Examples 🎖️](https://www.freecodecamp.org/news/learn-css-background-properties/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/learn-css-background-properties.md

**Comment by Miever1** [comment]
@miyaliu666 翻译好了，以后这个作者的系列文章我都会一一翻译，可以直接指给我

**Comment by Miever1** [comment]
<img width="948" alt="image" src="https://user-images.githubusercontent.com/49714091/124477819-0cf4a980-ddd7-11eb-85ec-892a40ec7fc0.png">
 @miyaliu666  然后这里我觉得他写的有点问题，可以讨论一下

**Comment by miyaliu666** [comment]
> @miyaliu666 翻译好了，以后这个作者的系列文章我都会一一翻译，可以直接指给我

你可以在[这里](https://www.freecodecamp.org/news/author/joy/)看想翻译他的哪篇文章，然后自己发 issue。

[这篇](https://chinese.freecodecamp.org/news/css-box-shadow-property-with-examples/)已经有人翻译过了。

**Comment by miyaliu666** [comment]
> <img alt="image" width="948" src="https://user-images.githubusercontent.com/49714091/124477819-0cf4a980-ddd7-11eb-85ec-892a40ec7fc0.png">
> 
> @miyaliu666 然后这里我觉得他写的有点问题，可以讨论一下

什么问题呢？你提出来，我去向英文编辑团队反馈，或者你直接发 issue 反馈。
