### ISSUE TITLE
[Auto] 通过创建计数器应用程序来学习 Redux

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#492]
- 原文网址：[Learn Redux by Making a Counter Application](https://www.freecodecamp.org/news/learn-redux-by-making-a-counter-application/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/learn-redux-by-making-a-counter-application.md

**Comment by Humilitas** [comment]
认领翻译。
