### ISSUE TITLE
[Auto] 如何设计你的 React 应用程序——2021 年编写 CSS 的 5 种方法

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#515]
- 原文网址：[How to Style Your React App – 5 Ways to Write CSS in 2021](https://www.freecodecamp.org/news/how-to-style-react-apps-with-css/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/how-to-style-react-apps-with-css.md

**Comment by luojiyin1987** [comment]
@miyaliu666   我来翻译

**Comment by luojiyin1987** [comment]
@miyaliu666  翻译完成
