### ISSUE TITLE
object-oriented-programming-concepts

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#52]
文章：[Object Oriented Programming Concepts: How to go from Zero to One with Objects](https://www.freecodecamp.org/news/object-oriented-concepts/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/edit/master/chinese/articles/object-oriented-programming-concepts.md)
PR 地址：
文章分类：前端
注意：译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将自己的新分支发 Pull Request。

**Comment by CoderSan1997** [comment]
认领校对
