### ISSUE TITLE
[Auto] 如何在 CSS 和 HTML 中使用 SVG 图像——初学者教程

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#530]
- 原文网址：[How to Use SVG Images in CSS and HTML – A Tutorial for Beginners](https://www.freecodecamp.org/news/use-svg-images-in-css-html/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/use-svg-images-in-css-html.md

**Comment by lzzlzz** [comment]
请问原文中用沙盒演示的代码示例应该如何在译文中引入啊？ @miyaliu666

**Comment by miyaliu666** [comment]
刚看到消息，如图，可以获得 iframe 链接。你翻译好了，我在 Ghost 发布的时候我来添加沙箱链接吧。稍后会邀请你注册成为专栏作者，专栏用的是 Ghost CMS。谢谢！

![image](https://user-images.githubusercontent.com/19358186/147938478-f322bb61-c70d-4913-82e6-3db16b81af8a.png)

**Comment by lzzlzz** [comment]
> 刚看到消息，如图，可以获得 iframe 链接。你翻译好了，我在 Ghost 发布的时候我来添加沙箱链接吧。稍后会邀请你注册成为专栏作者，专栏用的是 Ghost CMS。谢谢！
> 
> ![image](https://user-images.githubusercontent.com/19358186/147938478-f322bb61-c70d-4913-82e6-3db16b81af8a.png)

好的，我已经翻译好了，那麻烦您来添加沙箱链接了。
