### ISSUE TITLE
[Auto] Linux 符号链接教程——如何创建和删除符号链接

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#532]
- 原文网址：[Symlink Tutorial in Linux – How to Create and Remove a Symbolic Link](https://www.freecodecamp.org/news/symlink-tutorial-in-linux-how-to-create-and-remove-a-symbolic-link/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/symlink-tutorial-in-linux-how-to-create-and-remove-a-symbolic-link.md

**Comment by Humilitas** [comment]
认领翻译

**Comment by Humilitas** [comment]
认领翻译。
