### ISSUE TITLE
[Auto] 如何在 React 中使用 Axios：2021 年完全指南

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#533]
- 原文网址：[How To Use Axios With React: The Definitive Guide (2021)](https://www.freecodecamp.org/news/how-to-use-axios-with-react/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/how-to-use-axios-with-react.md

**Comment by luojiyin1987** [comment]
我来翻译

**Comment by luojiyin1987** [comment]
#576

**Comment by luojiyin1987** [comment]
@miyaliu666  已经翻译完了
