### ISSUE TITLE
[Auto] 如何使用 Node 后端创建 React 应用程序：完整指南

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#534]
- 原文网址：[How to Create a React App with a Node Backend: The Complete Guide](https://www.freecodecamp.org/news/how-to-create-a-react-app-with-a-node-backend-the-complete-guide/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/how-to-create-a-react-app-with-a-node-backend-the-complete-guide.md

**Comment by luojiyin1987** [comment]
我来翻译  @miyaliu666

**Comment by luojiyin1987** [comment]
#534

**Comment by luojiyin1987** [comment]
@miyaliu666  已经翻译完
