### ISSUE TITLE
[Auto] JavaScript 中的词法作用域——JS 中的作用域究竟是什么？

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#537]
- 原文网址：[Lexical Scope in JavaScript – What Exactly Is Scope in JS?](https://www.freecodecamp.org/news/javascript-lexical-scope-tutorial/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/javascript-lexical-scope-tutorial.md

**Comment by luojiyin1987** [comment]
@miyaliu666   改下 labels  的状态
