### ISSUE TITLE
[Auto] 为什么学习编程很难——以及如何让它更容易

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#538]
- 原文网址：[Why Learning to Code is Hard – And How to Make it Easier](https://www.freecodecamp.org/news/why-learning-to-code-is-hard-and-how-to-make-it-easier/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/why-learning-to-code-is-hard-and-how-to-make-it-easier.md

**Comment by frankflx** [comment]
认领翻译

**Comment by luojiyin1987** [comment]
认领

**Comment by luojiyin1987** [comment]
@miyaliu666  翻译完成
