### ISSUE TITLE
How To Host Your Personal Website for Free

### ISSUE THREAD

**Issue by jingruzhang** [freeCodeCamp/news-translation#55]
文章：[How To Host Your Personal Website for Free](https://medium.com/better-programming/how-to-host-your-personal-website-for-free-3101c4ab2e49)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/how-to-host-your-personal-website-for-free.md)
PR 地址：
文章分类：其他
注意：译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将自己的新分支发 Pull Request。

**Comment by ZhichengChen** [comment]
翻译认领

**Comment by miyaliu666** [comment]
认领校对

**Comment by miyaliu666** [comment]
Translation completed and published. Thanks!
