### ISSUE TITLE
[Auto] 什么是 .gitkeep？如何让 Git 追踪空文件夹

### ISSUE THREAD

**Issue by Humilitas** [freeCodeCamp/news-translation#557]
- 原文网址：[What is .gitkeep? How to Track and Push Empty Folders in Git](https://www.freecodecamp.org/news/what-is-gitkeep/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/what-is-gitkeep.md

**Comment by miyaliu666** [comment]
@Humilitas 你准备翻译这篇文章吗

**Comment by Humilitas** [comment]
> @Humilitas 你准备翻译这篇文章吗

是的
