### ISSUE TITLE
How to build a JSON API with Python

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#58]
文章：[How to build a JSON API with Python](https://www.freecodecamp.org/news/build-a-simple-json-api-in-python/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/build-a-simple-json-api-in-python.md)
PR 地址：
文章分类：Python
注意：译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将自己的新分支发 Pull Request。

**Comment by fearlessfe** [comment]
翻译认领

**Comment by fearlessfe** [comment]
翻译完成

**Comment by miyaliu666** [comment]
Translation completed and published. Thanks again!
