### ISSUE TITLE
How to enable ES6 (and beyond) syntax with Node and Express

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#6]
文章：[How to enable ES6 (and beyond) syntax with Node and Express](https://www.freecodecamp.org/news/how-to-enable-es6-and-beyond-syntax-with-node-and-express-68d3e11fe1ab/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/enable-es6-syntax-with-node-and-express.md)
PR 地址：[#33](https://github.com/freeCodeCamp/news-translation/pull/33)
文章分类：前端
注意：译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将自己的新分支发 Pull Request。

**Comment by zlv2s** [comment]
翻译认领

**Comment by miyaliu666** [comment]
Translation completed and published. Thanks!
