### ISSUE TITLE
How to build a real-time todo app with React Native

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#60]
文章：[How to build a real-time todo app with React Native](https://www.freecodecamp.org/news/how-to-build-a-real-time-todo-app-with-react-native-19a1ce15b0b3/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/how-to-build-a-real-time-todo-app-with-react-native.md)
PR 地址：
文章分类：前端
注意：译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将自己的新分支发 Pull Request。

**Comment by blackcai** [comment]
翻译认领

#62

**Comment by miyaliu666** [comment]
Translation completed and published. Thanks a lot!
