### ISSUE TITLE
[Auto]（Git 和 GitHub 教程——版本控制入门）

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#631]
- 原文网址：[Git and GitHub Tutorial – Version Control for Beginners](https://www.freecodecamp.org/news/git-and-github-for-beginners/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/git-and-github-for-beginners.md

**Comment by luojiyin1987** [comment]
@miyaliu666   我来翻译

**Comment by luojiyin1987** [comment]
#632
