### ISSUE TITLE
[Auto] 什么是编译器？面向初学者的 C 编译器解释

### ISSUE THREAD

**Issue by gyf11069** [freeCodeCamp/news-translation#647]
- 原文网址：[what-is-a-compiler-in-c](https://www.freecodecamp.org/news/what-is-a-compiler-in-c/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/what-is-a-compiler-in-c.md

**Comment by luojiyin1987** [comment]
@miyaliu666  我来翻译

**Comment by luojiyin1987** [comment]
@miyaliu666  已经翻译完
