### ISSUE TITLE
[Auto]（什么是虚拟机？如何在 Windows、Linux 和 Mac 上设置 VM？）

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#655]
- 原文网址：[What is a Virtual Machine And How to Setup a VM on Windows, Linux, and Mac](https://www.freecodecamp.org/news/what-is-a-virtual-machine-and-how-to-setup-a-vm-on-windows-linux-and-mac/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/what-is-a-virtual-machine-and-how-to-setup-a-vm-on-windows-linux-and-mac.md

**Comment by luojiyin1987** [comment]
@miyaliu666   我来翻译

**Comment by luojiyin1987** [comment]
@miyaliu666   已经翻译完
