### ISSUE TITLE
[Auto]（用 Python 构建 Discord 机器人，并免费托管）

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#656]
- 原文网址：[Python Discord Bot Tutorial – Code a Discord Bot And Host it for Free](https://www.freecodecamp.org/news/create-a-discord-bot-with-python/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/create-a-discord-bot-with-python.md

**Comment by luojiyin1987** [comment]
@miyaliu666   已经翻译完了
