### ISSUE TITLE
[Auto]（如何用 Husky 向 Git 添加 commit hook 以实现代码任务的自动化）

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#658]
- 原文网址：[How to Add Commit Hooks to Git with Husky to Automate Code Tasks](https://www.freecodecamp.org/news/how-to-add-commit-hooks-to-git-with-husky-to-automate-code-tasks/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/how-to-add-commit-hooks-to-git-with-husky-to-automate-code-tasks.md

**Comment by luojiyin1987** [comment]
@miyaliu666   我来翻译

**Comment by luojiyin1987** [comment]
@miyaliu666  已经翻译完成
