### ISSUE TITLE
[Auto]（框架和库的区别是什么）

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#659]
- 原文网址：[The Difference Between a Framework and a Library](https://www.freecodecamp.org/news/the-difference-between-a-framework-and-a-library-bd133054023f/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/the-difference-between-a-framework-and-a-library.md

**Comment by luojiyin1987** [comment]
@miyaliu666  翻译完成
