### ISSUE TITLE
[Auto]（如何开始对 JavaScript 代码进行单元测试）

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#660]
- 原文网址：[How to Start Unit Testing Your JavaScript Code](https://www.freecodecamp.org/news/how-to-start-unit-testing-javascript/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/how-to-start-unit-testing-javascript.md

**Comment by luojiyin1987** [comment]
@miyaliu666  我来翻译

**Comment by luojiyin1987** [comment]
@miyaliu666   已经翻译完
