### ISSUE TITLE
[Auto]（如何写好API文档）

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp/news-translation#693]
- 原文网址：[How to Write Good API Documentation](https://www.freecodecamp.org/news/how-to-write-api-documentation-like-a-pro/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/how-to-write-api-documentation-like-a-pro.md

**Comment by luojiyin1987** [comment]
@miyaliu666    已经翻译了

**Comment by miyaliu666** [comment]
好的，已经发布了，已修改小细节，谢谢！
