### ISSUE TITLE
These are the features in ES6 that you should know

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#7]
文章：[These are the features in ES6 that you should know](https://www.freecodecamp.org/news/these-are-the-features-in-es6-that-you-should-know-1411194c71cb/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/features-in-es6-should-know.md)
PR 地址：
文章分类：前端
注意：译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将自己的新分支发 Pull Request。

**Comment by jingruzhang** [comment]
duplicate of issue #1

**Comment by TechQuery** [comment]
@miyaliu666 @jingruzhang GitHub issue 不能删，但可以直接修改内容为新 issue 来复用。
