### ISSUE TITLE
[Auto]（JavaScript 模块）

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#702]
- 原文网址：[Modules in JavaScript – CommonJS and ESmodules Explained](https://www.freecodecamp.org/news/modules-in-javascript/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/modules-in-javascript.md

**Comment by miyaliu666** [comment]
@PapayaHUANG 这个 issue 没有问题，你可以认领啦

**Comment by PapayaHUANG** [comment]
@miyaliu666 oki
