### ISSUE TITLE
[Auto]（JavaScript中的闭包--用例子来解释）

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp/news-translation#705]
- 原文网址：[Closure in JavaScript – Explained with Examples](https://www.freecodecamp.org/news/javascript-closures-explained-with-example/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/javascript-closures-explained-with-example.md

**Comment by PapayaHUANG** [comment]
占坑～

**Comment by PapayaHUANG** [comment]
@miyaliu666 这篇翻译完啦～
