### ISSUE TITLE
[Auto]（如何用Travis CI在GitHub页面上托管一个Angular应用程序）

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp/news-translation#720]
- 原文网址：[How to Host an Angular Application on GitHub Pages with Travis CI](https://www.freecodecamp.org/news/host-an-angular-application-on-github-pages-with-travis-ci/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/host-an-angular-application-on-github-pages-with-travis-ci.md

**Comment by bauhauce** [comment]
@miyaliu666 翻译好了
