### ISSUE TITLE
[Auto]（什么是系统工程？初学者指南）

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp/news-translation#722]
- 原文网址：[What is Systems Engineering? A Beginner's Guide](https://www.freecodecamp.org/news/what-is-systems-engineering/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/what-is-systems-engineering.md

**Comment by luojiyin1987** [comment]
@miyaliu666   已经翻译完了 ，感觉文章比较水。

**Comment by miyaliu666** [comment]
@luojiyin1987 你有兴趣的话可以就这个标题写一篇完善些的文章
