### ISSUE TITLE
The React Handbook

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#75]
文章：[The React Handbook](https://www.freecodecamp.org/news/the-react-handbook-b71c27b0a795/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/the-react-handbook.md)
PR 地址：
注意：译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将自己的新分支发 Pull Request。

**Comment by fearlessfe** [comment]
翻译认领

**Comment by fearlessfe** [comment]
抱歉！没能继续翻译，也没有及时反馈。以后我还是选择翻译文章吧。

**Comment by XuQuan-nikkkki** [comment]
翻译认领

**Comment by miyaliu666** [comment]
提醒 @XuQuan-nikkkki 在翻译的时候可以添加”译者注“，对你认为 原文中不完善或者需要更新的知识点 加以说明。谢谢！

**Comment by XuQuan-nikkkki** [comment]
好的
