### ISSUE TITLE
[Auto]（此处替换为翻译的中文标题）

### ISSUE THREAD

**Issue by Hot1122** [freeCodeCamp/news-translation#756]
- 原文网址：[原文标题](https://www.freecodecamp.org/news/路由/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/文章文件名称.md

**Comment by luojiyin1987** [comment]
这时一个无效的 issues  @miyaliu666  @Hot1122 ,  麻烦请关闭。
