### ISSUE TITLE
[Auto]（Javascript中的原型和继承）

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp/news-translation#757]
- 原文网址：[JavaScript Prototypes and Inheritance – and Why They Say Everything in JS is an Object](https://www.freecodecamp.org/news/prototypes-and-inheritance-in-javascript/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/prototypes-and-inheritance-in-javascript.md

**Comment by PapayaHUANG** [comment]
@luojiyin1987 刚好看到，这篇已经翻译并发布了 [这里](https://chinese.freecodecamp.org/news/prototypes-and-inheritance-in-javascript/)
@miyaliu666 顺便我很好奇就是我们有避免重复的机制吗？hh 我也不知道问谁

**Comment by luojiyin1987** [comment]
@PapayaHUANG    我还没开始翻译。   
我一般是切回main 分支， 然后 `git  log  xxx.md`   
![image](https://user-images.githubusercontent.com/6524977/167079639-dafcf694-0fb9-4a4d-b9c1-7b8f89f5b1d1.png)

@miyaliu666    爬虫 action ，加个文件是否存在  就可以避免

**Comment by luojiyin1987** [comment]
已经有人翻译好了， 我不小心覆盖了， 怎样解决 ？ @miyaliu666

**Comment by miyaliu666** [comment]
最终是以专栏发布的文章为准，所以仓库里被覆盖了也问题不大，但是我也想知道有什么办法可以撤销覆盖，请教一下水歌呢 @TechQuery 

这是之前的 PR #752 

我刚才还弄了个 revert，不确定是不是对的方法，所以又把它删了。

**Comment by luojiyin1987** [comment]
@miyaliu666   合并一下代码
