### ISSUE TITLE
The definitive Node.js handbook

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#77]
文章：[The definitive Node.js handbook](https://www.freecodecamp.org/news/the-definitive-node-js-handbook-6912378afc6e/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/the-definitive-node-js-handbook.md)
PR 地址：

**Comment by logeast** [comment]
翻译认领

**Comment by blackcai** [comment]
翻译认领 #322

**Comment by miyaliu666** [comment]
谢谢 @blackcai  翻译这篇文章！

之前 @logeast 有认领，我没看到你的消息呢，不好意思。要认领其他文章的话，可以直接根据 readme 里的图文指南创建 pull request。

我们每周六下午 1 点 - 3 点（北京时间）组织在线技术翻译工作坊，欢迎大家[加入 Skype 会议室](https://join.skype.com/WNwhdeBLA1RT)，在工作坊参与讨论。

**Comment by luojiyin1987** [comment]
@miyaliu666   这个issue 可以关了。
