### ISSUE TITLE
[Auto]（JS reduce和reduceRight是怎么运作的？）

### ISSUE THREAD

**Issue by PapayaHUANG** [freeCodeCamp/news-translation#773]
- 原文网址：[JS reduce和reduceRight是怎么运作的？](https://www.freecodecamp.org/news/how-reduce-reduceright-works-javascript/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/how-reduce-reduceright-works-javascript.md

**Comment by PapayaHUANG** [comment]
@miyaliu666 这篇翻译完了

**Comment by miyaliu666** [comment]
已发布，谢谢 @PapayaHUANG 
正好这个知识点 我也有点迷糊，回头仔细看看~
