### ISSUE TITLE
The Vue Handbook: a thorough introduction to Vue.js

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#78]
文章：[The Vue Handbook: a thorough introduction to Vue.js](https://www.freecodecamp.org/news/the-vue-handbook-a-thorough-introduction-to-vue-js-1e86835d8446/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/the-vue-handbook-a-thorough-introduction-to-vue-js.md)
PR 地址：

**Comment by blackcai** [comment]
#154 认领

**Comment by miyaliu666** [comment]
建议 @blackcai 在翻译的时候结合 Vue.js 近期的更新 在译文中适当调整:)

**Comment by blackcai** [comment]
好的，我尽量。
