### ISSUE TITLE
Async Generators as an alternative to State Management

### ISSUE THREAD

**Issue by jingruzhang** [freeCodeCamp/news-translation#8]
文章：[Async Generators as an alternative to State Management](https://www.freecodecamp.org/news/async-generators-as-an-alternative-to-state-management/?fbclid=IwAR2Py7k7WayAE_zq4tkd99pj3oBP7scsKp9mZbPCtv_zJqvhN4eOVAef6M8)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/async-generators-as-alternative-to-state-management.md)
PR 地址：
文章分类：前端
注意：**译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将自己的新分支发 Pull Request**。

**Comment by miyaliu666** [comment]
Translation completed and published. Thanks!
