### ISSUE TITLE
Everything you need to know about CSS Variables

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#80]
文章：[Everything you need to know about CSS Variables](https://www.freecodecamp.org/news/everything-you-need-to-know-about-css-variables-c74d922ea855/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/everything-you-need-to-know-about-css-variables.md)
PR 地址：

**Comment by LolaWei** [comment]
翻译完啦！
