### ISSUE TITLE
[Auto]（通过例子来理解 Javascript 中的 Call, Apply和 Bind）

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp/news-translation#822]
- 原文网址：[How to Use the Call, Apply, and Bind Functions in JavaScript – with Code Examples](https://www.freecodecamp.org/news/understand-call-apply-and-bind-in-javascript-with-examples/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/understand-call-apply-and-bind-in-javascript-with-examples.md

**Comment by PapayaHUANG** [comment]
@miyaliu666 这篇翻译完啦
