### ISSUE TITLE
[Auto]（如何在机器学习中检测异常点 - 4种检测异常点的方法）

### ISSUE THREAD

**Issue by toudatouda** [freeCodeCamp/news-translation#864]
- 原文网址：[How to Detect Outliers in Machine Learning – 4 Methods for Outlier Detection](https://www.freecodecamp.org/news/how-to-detect-outliers-in-machine-learning/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/how-to-detect-outliers-in-machine-learning.md

**Comment by toudatouda** [comment]
closes #864

**Comment by miyaliu666** [comment]
> closes #864

仔细看一下 readme 里面的图文指南哦，应该是在你创建了 pull request 之后 在 pr 里面写 “closes #864”

**Comment by toudatouda** [comment]
@miyaliu666 翻译完成
