### ISSUE TITLE
[Auto]（如何在GitHub中自动生产 一个 Pull Request 检查列表）

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp/news-translation#869]
- 原文网址：[How to Create an Automated Pull Request Checklist in GitHub](https://www.freecodecamp.org/news/create-a-pr-checklist-in-github/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/create-a-pr-checklist-in-github.md

**Comment by miyaliu666** [comment]
这篇已经有人翻译了，直接在 Crowdin 翻译的

**Comment by luojiyin1987** [comment]
@miyaliu666   我又不看 Crowdin。
