### ISSUE TITLE
[Auto]（软件工程师写作技巧——如何成为一个更好的技术写作者）

### ISSUE THREAD

**Issue by Narcissus91** [freeCodeCamp/news-translation#880]
- 原文网址：[Writing Tips for Software Developers – How to Become a Better Tech Writer](https://www.freecodecamp.org/news/writing-tips-software-developers/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/writing-tips-software-developers.md

**Comment by HeZean** [comment]
Hi, I'm willing to work on it.
