### ISSUE TITLE
How to be a team player in the tech world

### ISSUE THREAD

**Issue by jingruzhang** [freeCodeCamp/news-translation#9]
文章：[How to be a team player in the tech world](https://www.freecodecamp.org/news/how-to-be-a-team-player-in-the-tech-world-c78aa9f4e898/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/be-team-player-in-the-tech-world.md)
PR 地址：
文章分类：职业发展
注意：**译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将自己的新分支发 Pull Request**。

**Comment by cisco08** [comment]
认领翻译
