### ISSUE TITLE
How to Turn Your Website into a Mobile App with 7 Lines of JSON

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#91]
文章：[How to Turn Your Website into a Mobile App with 7 Lines of JSON](https://www.freecodecamp.org/news/how-to-turn-your-website-into-a-mobile-app-with-7-lines-of-json-631c9c9895f5/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/how-to-turn-your-website-into-a-mobile-app-with-7-lines-of-json.md)
PR 地址：
注意：译者在 Fork 此仓库后，请先从自己的 master 分支上 git checkout -b "translate/文件名"，在新分支上做翻译，完成后将自己的新分支发 Pull Request。

**Comment by LianZhuotao** [comment]
OK了！

**Comment by miyaliu666** [comment]
Translation completed and published. Thanks!
