### ISSUE TITLE
[Auto]（如何用 JavaScript 搭建一个模态框）

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#967]
- 原文网址：[How to Build a Modal with JavaScript](https://www.freecodecamp.org/news/how-to-build-a-modal-with-javascript/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/how-to-build-a-modal-with-javascript.md

**Comment by miyaliu666** [comment]
@dake0913

**Comment by dake0913** [comment]
您好！您的邮件我已收到，我会尽快处理的。
 
                                                            马可人

**Comment by dake0913** [comment]
closes #967

**Comment by Soecka** [comment]
@dake0913
