### ISSUE TITLE
[Auto]（交互式课程中的资源 - React State 代码示例）

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#973]
- 原文网址：[How State Works in React – Explained with Code Examples](https://www.freecodecamp.org/news/what-is-state-in-react-explained-with-examples/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/what-is-state-in-react-explained-with-examples.md

**Comment by dake0913** [comment]
closes #973

**Comment by dake0913** [comment]
closes #973

**Comment by miyaliu666** [comment]
repeated
