### ISSUE TITLE
[Auto]（Go 语言手册）

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/news-translation#979]
- 原文网址：[The Go Handbook – Learn Golang for Beginners](https://www.freecodecamp.org/news/go-beginners-handbook/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/go-beginners-handbook.md

**Comment by miyaliu666** [comment]
上周有学员在公众号里留言说希望能看到 Go 语言手册，正好我们的英文专栏就发布了这篇文章！

**Comment by herosql** [comment]
@miyaliu666 这篇翻译完了

**Comment by miyaliu666** [comment]
谢谢 @herosql ，译文在你的主分支里 https://github.com/herosql/news-translation/blob/main/chinese/articles/go-beginners-handbook.md，需要 pull request 哦

**Comment by herosql** [comment]
@miyaliu666 已经提交 pull request
